### ISSUE TITLE
!needful

### ISSUE THREAD

**Issue by Arengo** [smoo7h/Pokemon_Go_Map_PWN#2]
I guess you know the content of that command.

**Comment by smoo7h** [comment]
just enter coordinates for the NE and SW corners of the square on a map that you want to scrape.

      <add key="oNeLat" value=""/>
      <add key="oNeLng" value=""/>
      <add key="oSwLat" value=""/>
      <add key="oSwLng" value=""/>

**Comment by Arengo** [comment]
@smoo7h Hey, thanks. Will try it on my map. Does your code have PokeAlarm support?

**Comment by smoo7h** [comment]
Just make sure you compile it first. 
It is also a stand-alone console application it is not directly connected to the rocketmap just connects the the MYSQL server.
